version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - rust-service
      - vector-db

  rust-service:
    build: ./rust-service
    ports:
      - "8081:8081"
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  vector-db:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
